### ISSUE TITLE
generate_measfile() returns: object 'folderpath' not found

### ISSUE THREAD

**Issue by dereckdemezquita** [saezlab/CARNIVAL#18]
Tried to rerun some code written just a couple of weeks ago. Getting this error now when generating the measurement file. 

I noticed that the `folderpath` variable is declared inside the `generate_measfile()` function but not defined.

Moreover, I cannot find the `generate_measfile()` in the source code you currently have available. Have you changed the name or otherwise?

I pasted my error below:

`> generate_measfile(measurements = TF_uniprot,
 \+ 				  topnumber = NULL,
\+ 				  write2folder = "measurements")
 Error in paste0(folderpath, "/meas_", drug, "_all.txt") :  object 'folderpath' not found`

**Comment by enio23** [comment]
Hello,

Yes indeed, generate_meas() function and few others have been removed since I had to adapt the CARNIVAL pipeline according to Bioconductor guidelines and requirements. In case you are integrating TF and pathway activity scores, I will soon add an example in the README about how one can do that. But for this I am waiting for the new release of Bioconductor packages where CARNIVAL and newest versions of PROGENy and DoRothEA packages will be there. This is expected to happen in the next few days within this mont but if you need any urgent help you can contact me at enio.gjerga@gmail.com.

Best,
