### ISSUE TITLE
Missining complete tutorial

### ISSUE THREAD

**Issue by michelegentili93** [saezlab/CARNIVAL#22]
Hi, I'd like to use this software for my research. Although I I can't find a complete tutorial or an example (including Dorothea and Progeny) through which I can understand the pipeline. I have a set of target perturbations and a gene expression matrix. How can I get the final signaling network ?

**Comment by adugourd** [comment]
Hello,

have you checked this tutorial here ? https://github.com/saezlab/CARNIVAL/blob/master/vignettes/CARNIVAL-vignette.pdf

If so do you mean you don't know how to run dorothea and progeny only ?

Cheers

**Comment by michelegentili93** [comment]
Thanks for the quick response :) My issue is how to prepare the input data.
In the vignette the object inputs (Network and pathways) are given, but
it's not that obvious how to generate them. I've tried to run progeny...
but it has only 11 pathways. So I'm wondering if there's a better way to
run CARNIVAL, provided that the only real input for the "user" is to
provide a list of perturbation and a gene expression matrix, from which
dorothea and progeny will compute the basic input for CARNIVAL.





Il giorno ven 14 ago 2020 alle ore 10:28 Aurelien Dugourd <
notifications@github.com> ha scritto:

**Comment by michelegentili93** [comment]
So little update:

I've the output of Dorothea -> a matrix that is pathways x patients.
However to use a weight object as input of CARNIVAL, I need weights on nodes of the network that are genes and not pathways. How can I have an output of DOROTHEA useful for CARNIVAL?

**Comment by ivanovaos** [comment]
@michelegentili93 let's try to figure it out together. 

> I've the output of Dorothea -> a matrix that is pathways x patients.
The output of DoRoThEA is a list of TFs, that can be combined with running e.g. VIPER to estimate TF activities. Progeny should generate a list of pathways activities. Do you mean here the output of Progeny then?

**Comment by Semple-bio** [comment]
Good day.
After skimming through many hundred commits, it seems the tutorial got truncated multiple times until the vignette looks like it does now. With the real life examples gone, there are only 2 binary small examples with little resemblance to real life data. For a first time user this makes it close to impossible to get the 'raw RNAseq counts' -> 'Carnival input' step right. Is there a new detailed real-life example in the making?

**Comment by enio23** [comment]
Maybe you can check this tutorial here: https://github.com/saezlab/transcriptutorial.

The current version of the vignette is limited in the description because a)The functionalities of the progeny and dorothea packages were not available in Bioconductor yet at the time when CARNIVAL package was submitted in Bioc; and b)Vignette example should be small case studies which should be solved within a limited amount of time. Also while using CARNIVAL we strongly recommend in obtaining a [CPLEX](https://www.ibm.com/products/ilog-cplex-optimization-studio) license (there's a free academic edition) for solving the CARNIVAL problems rather than the default solver ([lpSolve](https://cran.r-project.org/web/packages/lpSolve/index.html)) since the latter is only implemented to pass the necessary Bioconductor tests and can only handle small case-studies before running into memory issues.

The vignettes should be updated in the next CARNIVAL updates in Bioconductor but until then hope the tutorial I have shared to be of help to you.
