### ISSUE TITLE
How to use CARNIVAL to fit multiple conditions data

### ISSUE THREAD

**Issue by olapuentesantana** [saezlab/CARNIVAL#77]
Hello,

I am interest in running CARNIVAL on multiple conditions data.

I have found a branch in which this aspect was investigated, however unsure whether is the most suitable way to perform this task.

https://github.com/saezlab/CARNIVAL/tree/multiple_conditions_carnival

I would appreciate if you have any suggestions in this respect.

Cheers,
Óscar

**Comment by gabora** [comment]
Dear @olapuentesantana ,

we used to have a multi-condition version (https://github.com/saezlab/CARNIVAL/tree/multiple_conditions_carnival) of CARNIVAL. But then we had a major reformulation of the package and these features were left out due to lack of interest and the original author left the group. 

We are discussing at the moment if this will be continued and if so when. 

best,
Attila

**Comment by gabora** [comment]
Multicondition carnival is now implemented in Corneto. 
https://github.com/saezlab/corneto
